import { Octokit } from "octokit";

// We use Octokit directly for GitHub API calls since the official
// GitHub MCP server requires Docker. This follows the same MCP tool
// interface pattern so you can swap to the full MCP server later.

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

/**
 * MCP-style tool definitions for GitHub operations.
 * These mirror what @modelcontextprotocol/server-github exposes.
 */
export const githubTools = {
  /**
   * Create a PR review comment on a specific PR
   */
  async create_pr_review_comment({ owner, repo, pull_number, body }) {
    const response = await octokit.rest.pulls.createReview({
      owner,
      repo,
      pull_number: parseInt(pull_number),
      body,
      event: "COMMENT",
    });
    return {
      success: true,
      review_id: response.data.id,
      html_url: response.data.html_url,
      submitted_at: response.data.submitted_at,
    };
  },

  /**
   * Create a GitHub issue with the review findings
   */
  async create_issue({ owner, repo, title, body, labels }) {
    const response = await octokit.rest.issues.create({
      owner,
      repo,
      title,
      body,
      labels: labels || ["code-review", "automated"],
    });
    return {
      success: true,
      issue_number: response.data.number,
      html_url: response.data.html_url,
    };
  },

  /**
   * List open PRs in a repo so user can pick one to comment on
   */
  async list_pull_requests({ owner, repo, state = "open" }) {
    const response = await octokit.rest.pulls.list({
      owner,
      repo,
      state,
      per_page: 20,
    });
    return response.data.map((pr) => ({
      number: pr.number,
      title: pr.title,
      author: pr.user.login,
      created_at: pr.created_at,
      html_url: pr.html_url,
    }));
  },

  /**
   * Validate that a GitHub token has access to a repo
   */
  async validate_repo({ owner, repo }) {
    try {
      const response = await octokit.rest.repos.get({ owner, repo });
      return { valid: true, full_name: response.data.full_name, private: response.data.private };
    } catch (err) {
      return { valid: false, error: err.message };
    }
  },
};

/**
 * Format a structured review result into a GitHub markdown comment
 */
export function formatReviewAsMarkdown(review, meta = {}) {
  const severityEmoji = { critical: "🔴", high: "🟠", medium: "🟡", low: "🟢" };
  const typeLabel = {
    bug: "Bug", security: "Security", performance: "Performance",
    style: "Style", ux: "UX", accessibility: "Accessibility", architecture: "Architecture",
  };

  const issueRows = review.issues
    .map(
      (i) =>
        `### ${severityEmoji[i.severity] || "⚪"} ${i.title}\n` +
        `**Type:** ${typeLabel[i.type] || i.type} · **Severity:** ${i.severity}\n\n` +
        `${i.description}\n\n` +
        (i.line ? `**Line:** ${i.line}\n\n` : "") +
        `**Suggestion:** ${i.suggestion}`
    )
    .join("\n\n---\n\n");

  const positives = review.positives?.length
    ? `\n\n### ✅ What's good\n${review.positives.map((p) => `- ${p}`).join("\n")}`
    : "";

  const snippet = review.refactoredSnippet
    ? `\n\n### 💡 Suggested refactor\n\`\`\`\n${review.refactoredSnippet}\n\`\`\``
    : "";

  return `## 🤖 Automated Code Review
> Powered by Gemini 1.5 Flash · ${meta.filename || "submitted code"} · ${new Date().toUTCString()}

**Overall severity:** ${severityEmoji[review.severity] || "⚪"} ${review.severity?.toUpperCase()}
**Language:** ${review.language || "unknown"}

### Summary
${review.summary}

---

## Issues Found (${review.issues.length})

${issueRows || "_No issues found — great work!_"}
${positives}${snippet}

---
*Generated by [Code Reviewer](https://github.com) — review all suggestions before merging.*`;
}